const STORAGE_KEY = 'kanken2-progress';
const CATEGORY_LABELS = {all:'全分野',reading:'読み',writing:'書き取り',idiom:'四字熟語',antonym:'対義語・類義語',radical:'部首',structure:'熟語構成',correction:'誤字訂正'};
const state = { questions: [], index: 0, results: [], revealed: false };
const $ = selector => document.querySelector(selector);
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}}catch{return {}}}
function saveProgress(progress){localStorage.setItem(STORAGE_KEY, JSON.stringify(progress))}
function showScreen(id){document.querySelectorAll('.screen').forEach(screen => screen.classList.toggle('active', screen.id === id))}
function shuffle(items){return [...items].sort(() => Math.random() - .5)}
function updateHome(){const progress=loadProgress();const entries=Object.values(progress);$('#weak-count').textContent=entries.filter(item=>item.incorrect>item.correct).length;$('#total-answered').textContent=entries.reduce((sum,item)=>sum+item.correct+item.incorrect,0)}
function startQuiz(){const category=$('#category').value;const count=Number($('#question-count').value);const pool=QUESTIONS.filter(question=>category==='all'||question.category===category);state.questions=shuffle(pool).slice(0,count);state.index=0;state.results=[];state.revealed=false;if(!state.questions.length)return;showScreen('quiz');renderQuestion()}
function renderQuestion(){const question=state.questions[state.index];state.revealed=false;$('#progress-text').textContent=`${state.index+1} / ${state.questions.length}`;$('#progress-fill').style.width=`${((state.index)/state.questions.length)*100}%`;$('#quiz-category').textContent=question.categoryLabel;$('#quiz-streak').textContent=`${state.results.filter(result=>result.known).length}問できた`;$('#prompt').textContent=question.prompt;$('#answer').textContent=question.answer;$('#explanation').textContent=question.explanation;$('#answer-panel').hidden=true;$('#reveal-button').hidden=false;const choices=$('#choices');choices.innerHTML='';(question.choices||[]).forEach(choice=>{const item=document.createElement('div');item.className='choice';item.textContent=choice;choices.appendChild(item)})}
function revealAnswer(){state.revealed=true;$('#answer-panel').hidden=false;$('#reveal-button').hidden=true}
function judge(known){if(!state.revealed)return;const question=state.questions[state.index];state.results.push({question,known});const progress=loadProgress();const previous=progress[question.id]||{correct:0,incorrect:0};progress[question.id]={correct:previous.correct+(known?1:0),incorrect:previous.incorrect+(known?0:1),lastAnsweredAt:new Date().toISOString()};saveProgress(progress);if(state.index<state.questions.length-1){state.index+=1;renderQuestion()}else finishQuiz()}
function finishQuiz(){const known=state.results.filter(result=>result.known).length;$('#result-known').textContent=known;$('#result-total').textContent=state.results.length;$('#result-message').textContent=known===state.results.length?'全問できました。':'分からなかった問題を復習リストに残しました。';const list=$('#review-list');list.innerHTML='';state.results.filter(result=>!result.known).forEach(result=>{const item=document.createElement('div');item.className='review-item';item.innerHTML=`<strong>${result.question.prompt}</strong><span>答え：${result.question.answer}</span>`;list.appendChild(item)});$('#progress-fill').style.width='100%';showScreen('result');updateHome()}
$('#start-button').addEventListener('click',startQuiz);$('#reveal-button').addEventListener('click',revealAnswer);$('#known-button').addEventListener('click',()=>judge(true));$('#unknown-button').addEventListener('click',()=>judge(false));$('#quit-button').addEventListener('click',()=>{showScreen('home');updateHome()});$('#again-button').addEventListener('click',startQuiz);$('#result-home-button').addEventListener('click',()=>{showScreen('home');updateHome()});$('#reset-button').addEventListener('click',()=>{if(confirm('学習履歴を削除しますか？')){localStorage.removeItem(STORAGE_KEY);updateHome()}});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));updateHome();
