const STORAGE_KEY = 'kanken2-progress';
const CATEGORY_LABELS = {all:'全分野',weak:'苦手問題のみ',reading:'読み',writing:'書き取り',idiom:'四字熟語',antonym:'対義語・類義語',radical:'部首',structure:'熟語構成',correction:'誤字訂正'};
var state = { questions: [], index: 0, results: [], revealed: false, retryIds: new Set() };
const $ = selector => document.querySelector(selector);
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}}catch{return {}}}
function saveProgress(progress){localStorage.setItem(STORAGE_KEY, JSON.stringify(progress))}
function showScreen(id){document.querySelectorAll('.screen').forEach(screen => screen.classList.toggle('active', screen.id === id))}
function shuffle(items){return [...items].sort(() => Math.random() - .5)}
const REVIEW_INTERVAL_DAYS=[1,3,7,14,30];
function reviewDue(item,now=Date.now()){if(!item||!item.incorrect)return false;const dueAt=Date.parse(item.nextReviewAt||item.lastAnsweredAt||0);return !dueAt||dueAt<=now}
function updateHome(){const progress=loadProgress();const entries=Object.values(progress);$('#weak-count').textContent=entries.filter(item=>reviewDue(item)).length;$('#total-answered').textContent=entries.reduce((sum,item)=>sum+item.correct+item.incorrect,0)}
function startQuiz(){const category=$('#category').value;const count=Number($('#question-count').value);const progress=loadProgress();const pool=QUESTIONS.filter(question=>category==='all'||(category==='weak'&&reviewDue(progress[question.id]))||question.category===category);if(!pool.length){alert(category==='weak'?'今日の復習問題はありません。間違えた問題は復習時期になると、ここに表示されます。':'この分野には問題がありません。');return}state.questions=shuffle(pool).slice(0,count);state.index=0;state.results=[];state.revealed=false;state.retryIds=new Set();showScreen('quiz');renderQuestion()}
const MEANING_REDUNDANT_CATEGORIES=new Set(['idiom','correction','writing']);
function renderQuestion(){const question=state.questions[state.index];state.revealed=false;state.choicePicked=false;$('#progress-text').textContent=`${state.index+1} / ${state.questions.length}`;$('#progress-fill').style.width=`${((state.index)/state.questions.length)*100}%`;$('#quiz-category').textContent=question.categoryLabel;$('#quiz-streak').textContent=`${state.results.filter(result=>result.known).length}問正解`;$('#prompt').textContent=question.prompt;const showWritingHint=question.category==='writing'&&Boolean(question.meaning);$('#writing-hint').hidden=!showWritingHint;$('#writing-hint-text').textContent=showWritingHint?question.meaning:'';renderAnswer(question);const showMeaning=!MEANING_REDUNDANT_CATEGORIES.has(question.category)&&question.meaning;$('#meaning-block').hidden=!showMeaning;$('#meaning').textContent=question.meaning||'';const showExample=Boolean(question.example);$('#example-block').hidden=!showExample;$('#example').textContent=question.example||'';$('#explanation').textContent=question.explanation;$('#answer-panel').hidden=true;const hasChoices=Boolean((question.choices||[]).length);$('#reveal-button').hidden=hasChoices;$('#self-judge-buttons').hidden=true;$('#auto-result').hidden=true;$('#override-block').hidden=true;$('#next-button').hidden=true;const recallInput=$('#recall-input');recallInput.hidden=hasChoices;recallInput.value='';$('#reveal-button').disabled=!hasChoices;$('#recall-block').hidden=hasChoices;const choices=$('#choices');choices.innerHTML='';shuffle(question.choices||[]).forEach(choice=>{const item=document.createElement('div');item.className='choice';item.textContent=choice;item.addEventListener('click',()=>pickChoice(question,item,choice));choices.appendChild(item)})}
function pickChoice(question,item,choice){if(state.choicePicked)return;state.choicePicked=true;const isCorrect=choice===question.answer;item.classList.add(isCorrect?'correct':'incorrect');if(!isCorrect){Array.from($('#choices').children).find(el=>el.textContent===question.answer)?.classList.add('correct')}Array.from($('#choices').children).forEach(el=>el.classList.add('disabled'));recordResult(question,isCorrect);revealAnswer();showAutoResult(isCorrect)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
// 対義語・類義語や書き取りの答えは、読めないと確認しようがない漢字語が
// 多いため、読みが分かっている場合はルビを振って表示する。
// 誤字訂正は「誤X→正Y」形式のうちYの部分だけにルビを振る。
function renderAnswer(question){const el=$('#answer');if(question.category==='correction'&&question.correctionParts){const{wrongWord,correctWord,correctReading}=question.correctionParts;const correctHtml=correctReading?`<ruby>${escapeHtml(correctWord)}<rt>${escapeHtml(correctReading)}</rt></ruby>`:escapeHtml(correctWord);el.innerHTML=`誤 ${escapeHtml(wrongWord)} → 正 ${correctHtml}`;return}if(question.answerReading){el.innerHTML=`<ruby>${escapeHtml(question.answer)}<rt>${escapeHtml(question.answerReading)}</rt></ruby>`;return}el.textContent=question.answer}
function normalizeAnswer(value){return String(value||'').normalize('NFKC').trim().replace(/[\s　。、，．・「」『』]/g,'').replace(/[ァ-ヶ]/g,char=>String.fromCharCode(char.charCodeAt(0)-0x60))}
function acceptedAnswers(question){if(question.acceptedAnswers&&question.acceptedAnswers.length)return question.acceptedAnswers.map(normalizeAnswer);const answers=[question.answer];if(question.category==='correction'){const match=question.answer.match(/正\s+(.+)$/);if(match)answers.push(match[1])}return answers.map(normalizeAnswer)}
function showAutoResult(isCorrect){const resultLabel=$('#auto-result');resultLabel.hidden=false;resultLabel.textContent=isCorrect?'◯ 正解':'✕ 不正解';resultLabel.className=`auto-result ${isCorrect?'correct':'incorrect'}`;$('#next-button').hidden=false;$('#override-block').hidden=isCorrect}
function revealAnswer(){if((state.revealed&&!state.choicePicked)||($('#reveal-button').disabled&&!state.choicePicked))return;state.revealed=true;const input=$('#recall-input').value.trim();$('#recall-display').textContent=input;$('#answer-panel').hidden=false;$('#reveal-button').hidden=true;$('#self-judge-buttons').hidden=true;if(!state.choicePicked){const question=state.questions[state.index];const isCorrect=acceptedAnswers(question).includes(normalizeAnswer(input));recordResult(question,isCorrect);showAutoResult(isCorrect)}}
function applyProgress(question,known,progress){const previous=progress[question.id]||{correct:0,incorrect:0,streak:0};const now=new Date();const streak=known?(previous.streak||0)+1:0;const intervalDays=known?REVIEW_INTERVAL_DAYS[Math.min(streak-1,REVIEW_INTERVAL_DAYS.length-1)]:0;progress[question.id]={correct:previous.correct+(known?1:0),incorrect:previous.incorrect+(known?0:1),streak,lastResult:known?'correct':'incorrect',lastAnsweredAt:now.toISOString(),nextReviewAt:new Date(now.getTime()+intervalDays*86400000).toISOString()}}
function recordResult(question,known){state.results.push({question,known});const progress=loadProgress();applyProgress(question,known,progress);saveProgress(progress);if(!known&&!state.retryIds.has(question.id)){state.retryIds.add(question.id);state.questions.push(question)}}
// 対義語・類義語や誤字訂正は正解が1つしか登録されていない語もあり、辞書的に
// 妥当な別解を書いても自動採点で不正解になることがある。想起入力は既に
// 必須にしているため、ここでの自己判定は「何も考えず正解にする」余地がなく、
// 書いた回答と模範解答を見比べた上での訂正として扱ってよい。
function overrideResult(){if(!state.results.length)return;const last=state.results[state.results.length-1];if(last.known)return;const question=last.question;const progress=loadProgress();const entry=progress[question.id];if(entry){entry.correct-=last.known?1:0;entry.incorrect-=last.known?0:1}last.known=true;applyProgress(question,true,progress);saveProgress(progress);showAutoResult(true);$('#auto-result').textContent='◯ 正解（自分で訂正）'}
function advance(){if(state.index<state.questions.length-1){state.index+=1;renderQuestion()}else finishQuiz()}
function judge(known){if(!state.revealed||state.choicePicked)return;recordResult(state.questions[state.index],known);advance()}
function finishQuiz(){const known=state.results.filter(result=>result.known).length;$('#result-known').textContent=known;$('#result-total').textContent=state.results.length;$('#result-message').textContent=known===state.results.length?'全問正解です。':'不正解だった問題を復習リストに残しました。';const list=$('#review-list');list.innerHTML='';state.results.filter(result=>!result.known).forEach(result=>{const item=document.createElement('div');item.className='review-item';item.innerHTML=`<strong>${result.question.prompt}</strong><span>答え：${result.question.answer}</span>`;list.appendChild(item)});$('#progress-fill').style.width='100%';showScreen('result');updateHome()}
$('#start-button').addEventListener('click',startQuiz);$('#reveal-button').addEventListener('click',revealAnswer);$('#recall-input').addEventListener('input',()=>{$('#reveal-button').disabled=!$('#recall-input').value.trim()});$('#recall-input').addEventListener('keydown',event=>{if(event.key==='Enter'&&!$('#reveal-button').disabled)revealAnswer()});$('#next-button').addEventListener('click',advance);$('#override-button').addEventListener('click',overrideResult);$('#quit-button').addEventListener('click',()=>{showScreen('home');updateHome()});$('#again-button').addEventListener('click',startQuiz);$('#result-home-button').addEventListener('click',()=>{showScreen('home');updateHome()});$('#reset-button').addEventListener('click',()=>{if(confirm('学習履歴を削除しますか？')){localStorage.removeItem(STORAGE_KEY);updateHome()}});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));updateHome();
